Uma empresa de viagens gostaria de melhorar os seus resultados financeiros atuando no
índice de cancelamento de passagens compradas, para isso ela necessita entender o perfil
dos usuários com maior propensão a cancelamento e indicar esses possíveis clientes no
momento da venda de uma nova passagem.
Com base neste desafio:
1) Quais as características que aumentam o risco de um cancelamento?
2) Proponha uma maneira de indicar clientes com alto risco de cancelamento no
momento de uma venda.
Expectativa de entrega:
1. Construir uma apresentação dos resultados
2. Material utilizado para análise (códigos,etc)


Variáveis:
- Created: horário de registro do ticket.  
- CancelTime: hora em que o passageiro cancelou a passagem, se aplicável.  
- DepartureTime: horário de partida programado para a viagem.  
- BillID: o identificador exclusivo da transação de compra.  
- TicketID: o identificador exclusivo do ticket.  
- ReserveStatus: o status do pagamento do cliente.  
- UserID: o identificador exclusivo do usuário.  
- Male: indica se o bilhete pertence ou não a um passageiro do sexo masculino.  
- Price: o preço do bilhete sem descontos.  
- CouponDiscount: desconto aplicado pelo passageiro na passagem.  
- From: a origem da viagem.  
- To: o destino da viagem.  
- Domestic: Indica se a viagem é nacional ou internacional.  
- VehicleType: especifica detalhes sobre o meio de transporte.  
- VehicleClass: indica se o veículo é de primeira classe ou não.  
- Vehicle: especifica o tipo de veículo.  
- Cancel: indica se o ticket foi cancelado ou não.  
- HashPassportNumber_p: versão com hash do número do passaporte.  
- HashEmail: versão com hash do endereço de e-mail.  
- BuyerMobile: versão com hash do número do celular do comprador.  
- NationalCode: versão hash do número de identificação nacional.  
- TripReason: o motivo da viagem.

# Pacotes e leitura dos dados

In [226]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings


warnings.filterwarnings("ignore")
pd.options.display.float_format = '{:.4f}'.format

In [202]:
df = pd.read_csv('train_data.csv', parse_dates=['Created','DepartureTime','CancelTime'],
encoding='utf-8')

In [203]:
df.head()

,Created,CancelTime,DepartureTime,BillID,TicketID,ReserveStatus,UserID,Male,Price,CouponDiscount,...,Domestic,VehicleType,VehicleClass,TripReason,Vehicle,Cancel,HashPassportNumber_p,HashEmail,BuyerMobile,NationalCode
0,2022-10-23 09:38:49.110,NaT,2022-11-02 23:59:00,39710203,1091777.0000,5,122885.0000,True,6600000.0000,34425.0000,...,1,NaN,False,Work,Plane,0,NaN,66c7f29e3b92f3b77e20830ac29e7758037a53d2238a5b...,764974891906,477368495
1,2022-08-15 14:51:43.160,NaT,2022-08-18 04:15:00,38689463,1070902.0000,5,876925.0000,True,9500000.0000,0.0000,...,1,NaN,False,Int,Plane,0,NaN,b24634843858a4175d03422aa9e7211ec3b9f3ce4c481c...,27479149496,15987669
2,2022-09-20 17:25:27.250,NaT,2022-09-21 11:00:00,39245173,7624237.0000,3,916640.0000,False,2000000.0000,0.0000,...,1,VIP 2+1,True,Work,Bus,0,NaN,NaN,323657282999,667640412
3,2022-06-25 11:32:53.980,NaT,2022-06-26 08:30:00,37957585,2867547.0000,2,NaN,False,40000.0000,0.0000,...,1,3 ستاره اتوبوسي,NaN,Int,Train,0,NaN,NaN,169459057632,392476186
4,2022-06-01 11:30:53.633,NaT,2022-06-02 23:00:00,37584530,7212559.0000,3,NaN,True,1130000.0000,0.0000,...,1,اسکانیا تک صندلی ۳۱نفره,True,Int,Bus,0,NaN,NaN,408595008421,79497837

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101017 entries, 0 to 101016
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Created               101017 non-null  datetime64[ns]
 1   CancelTime            15326 non-null   datetime64[ns]
 2   DepartureTime         101017 non-null  datetime64[ns]
 3   BillID                101017 non-null  int64
 4   TicketID              101017 non-null  float64
 5   ReserveStatus         101017 non-null  int64
 6   UserID                42543 non-null   float64
 7   Male                  101017 non-null  bool
 8   Price                 101017 non-null  float64
 9   CouponDiscount        101017 non-null  float64
 10  From                  101017 non-null  object
 11  To                    101017 non-null  object
 12  Domestic              101017 non-null  int64
 13  VehicleType           93473 non-null   object
 14  VehicleClass          62567 non-null   object
 15  TripReason            101017 non-null  object
 16  Vehicle               101017 non-null  object
 17  Cancel                101017 non-null  int64
 18  HashPassportNumber_p  862 non-null     object
 19  HashEmail             43084 non-null   object
 20  BuyerMobile           101017 non-null  int64
 21  NationalCode          101017 non-null  int64
dtypes: bool(1), datetime64[ns](3), float64(4), int64(6), object(8)
memory usage: 16.3+ MB

# Organização e Limpeza dos dados

## Informações sobre os dados faltantes

In [205]:
df.isnull().sum()/len(df)

Created                0.0000
CancelTime             0.8483
DepartureTime          0.0000
BillID                 0.0000
TicketID               0.0000
ReserveStatus          0.0000
UserID                 0.5789
Male                   0.0000
Price                  0.0000
CouponDiscount         0.0000
From                   0.0000
To                     0.0000
Domestic               0.0000
VehicleType            0.0747
VehicleClass           0.3806
TripReason             0.0000
Vehicle                0.0000
Cancel                 0.0000
HashPassportNumber_p   0.9915
HashEmail              0.5735
BuyerMobile            0.0000
NationalCode           0.0000
dtype: float64

## Tratando variável Created

In [206]:
# Separando a coluna em mês, dia e hora
df['Created_month'] = df['Created'].dt.month
df['Created_day'] = df['Created'].dt.day
df['Created_hour'] = df['Created'].dt.hour

# Dropando a variável
df.drop('Created', axis= 1, inplace = True)

## Tratando variável CancelTime

In [207]:
# Separando as colunas em mês, dia e hora
df['Canceltime_month'] = df['CancelTime'].dt.month
df['Canceltime_day'] = df['CancelTime'].dt.day
df['Canceltime_hour'] = df['CancelTime'].dt.hour

# Retornando os NaT como 0
df['Canceltime_month'] = df['Canceltime_month'].apply(lambda x: 0 if pd.isnull(x) else x)
df['Canceltime_day'] = df['Canceltime_day'].apply(lambda x: 0 if pd.isnull(x) else x)
df['Canceltime_hour'] = df['Canceltime_hour'].apply(lambda x: 0 if pd.isnull(x) else x)

# Dropando a variável
df.drop('CancelTime',axis = 1, inplace= True)

## Tratando variável DepartureTime

In [208]:
# Separando a coluna DepartureTime em mês, dia e hora
df['DepartureTime_month'] = df['DepartureTime'].dt.month
df['DepartureTime_day'] = df['DepartureTime'].dt.day
df['DepartureTime_hour'] = df['DepartureTime'].dt.hour

# Dropando a variável
df.drop('DepartureTime',axis = 1, inplace= True)

## Tratando variável UserID

In [209]:
df['UserID'] = df['UserID'].apply(lambda x: 0 if pd.isnull(x) else 1)

## Tratando variável CouponDiscount

In [210]:
df['CouponDiscount'] = df['CouponDiscount'].apply(lambda x: 1 if x > 0 else 0)

## Tratando variável VehicleType

In [211]:
def Vehicle(row):
    if row['Vehicle'] in ['Bus', 'Train']:
        return 'Land'
    else:
        return 'Air'

In [212]:
df['VehicleType']= df.apply(Vehicle, axis = 1)

## Tratando variável VehicleClass

### Identificando quais são os tipos de veículo correspondentes aos valores NaN

In [213]:
# Checando qual tipo de veículo corresponde aos NaN da variável 'VehicleClass'

df[df['VehicleClass'].isna()]['Vehicle'].value_counts()

Vehicle
Train    38450
Name: count, dtype: int64

In [214]:
df['VehicleClass'] = pd.to_numeric(df['VehicleClass'], errors='coerce').astype('Int64')

In [215]:
# Criando um DF para classificar a variável VehicleClass
df_VC = df.drop(['BillID', 'TicketID','From','To','HashPassportNumber_p','HashEmail','BuyerMobile','NationalCode','Created_month','Created_day','Created_hour',
                 'Canceltime_month','Canceltime_day','Canceltime_hour','DepartureTime_month','DepartureTime_day','DepartureTime_hour', 'Cancel'], axis = 1)

# Filtrar registros com e sem VehicleClass
df_train = df_VC[df_VC['Vehicle'] == 'Train']  # Dados de trem (todas as VehicleClass são nulas)
df_others = df_VC[df_VC['Vehicle'] != 'Train']  # Dados de outras categorias de veículo

# Separar os dados completos (não nulos)
df_with_class = df_others[df_others['VehicleClass'].notnull()]  # Dados completos
df_missing_class = df_train  # Todos os registros de trem estão nulos

In [216]:
# Preparar as variáveis preditoras (X) e a variável alvo (y)
X = df_with_class.drop(['VehicleClass'], axis=1)
y = df_with_class['VehicleClass']

# Transformar as variáveis categóricas em dummies
X = pd.get_dummies(X, drop_first=True)

In [217]:
# Dividir o dataset em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Treinar o modelo
rfc = RandomForestClassifier(random_state=101, n_estimators=100)
rfc.fit(X_train, y_train)

# Avaliar o modelo
y_pred = rfc.predict(X_test)

print("Relatório de Classificação:\n", classification_report(y_test, y_pred),
      '\n\n',
      "Acurácia do modelo:", accuracy_score(y_test, y_pred))

Relatório de Classificação:
               precision    recall  f1-score   support

         0.0       0.96      0.87      0.92      4736
         1.0       0.96      0.99      0.97     14035

    accuracy                           0.96     18771
   macro avg       0.96      0.93      0.95     18771
weighted avg       0.96      0.96      0.96     18771


 Acurácia do modelo: 0.9602045708806137

In [218]:
# Previsão para os dados de trem
X_missing = df_missing_class.drop(['VehicleClass'], axis=1)
X_missing = pd.get_dummies(X_missing, drop_first=True)

# Reindexar para garantir a mesma estrutura de colunas
X_missing = X_missing.reindex(columns=X.columns, fill_value=0)

# Fazer a previsão para todos os registros de trem
predicted_classes = rfc.predict(X_missing)

# Adicionar as previsões ao DataFrame original
df.loc[df['Vehicle'] == 'Train', 'VehicleClass'] = predicted_classes

# Modelagem

In [219]:
df_final = df.drop(['BillID', 'TicketID','From','To','HashPassportNumber_p','HashEmail','BuyerMobile','NationalCode','Created_month','Created_day','Created_hour',
                 'Canceltime_month','Canceltime_day','Canceltime_hour','DepartureTime_month','DepartureTime_day','DepartureTime_hour'], axis = 1)

In [220]:
df_final.head()

,ReserveStatus,UserID,Male,Price,CouponDiscount,Domestic,VehicleType,VehicleClass,TripReason,Vehicle,Cancel
0,5,1,True,6600000.0000,1,1,Air,0,Work,Plane,0
1,5,1,True,9500000.0000,0,1,Air,0,Int,Plane,0
2,3,1,False,2000000.0000,0,1,Land,1,Work,Bus,0
3,2,0,False,40000.0000,0,1,Land,0,Int,Train,0
4,3,0,True,1130000.0000,0,1,Land,1,Int,Bus,0

In [221]:
df_final_dummies = pd.get_dummies(df_final, columns = ['ReserveStatus','UserID', 'Male', 'CouponDiscount','Domestic', 
                                                       'VehicleType', 'VehicleClass', 'TripReason', 'Vehicle'], drop_first= True)

In [223]:
df_final_dummies.head(10)

,Price,Cancel,ReserveStatus_3,ReserveStatus_4,ReserveStatus_5,UserID_1,Male_True,CouponDiscount_1,Domestic_1,VehicleType_Land,VehicleClass_1,TripReason_Work,Vehicle_InternationalPlane,Vehicle_Plane,Vehicle_Train
0,6600000.0000,0,False,False,True,True,True,True,True,False,False,True,False,True,False
1,9500000.0000,0,False,False,True,True,True,False,True,False,False,False,False,True,False
2,2000000.0000,0,True,False,False,True,False,False,True,True,True,True,False,False,False
3,40000.0000,0,False,False,False,False,False,False,True,True,False,False,False,False,True
4,1130000.0000,0,True,False,False,False,True,False,True,True,True,False,False,False,False
5,940000.0000,0,True,False,False,True,True,True,True,True,True,True,False,False,False
6,9289000.0000,0,False,False,True,True,True,False,True,False,False,True,False,True,False
7,2480000.0000,0,True,False,False,True,True,False,True,True,True,True,False,False,False
8,1220000.0000,0,True,False,False,True,True,False,True,True,True,True,False,False,False
9,1300000.0000,0,True,False,False,True,True,False,True,True,True,False,False,False,False

In [225]:
X = df_final_dummies.drop('Cancel',axis=1)
y = df_final_dummies['Cancel']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

## Função para exibição das métricas

In [227]:
def metricas(y_test, pred):
    print('\033[1m  Relatório de classificação:\033[0m' '\n', classification_report(y_test,pred), '\n'
      '\033[1m  Matriz de confusão: \033[0m' '\n', confusion_matrix(y_test,pred), '\n \n'
      '\033[1m  Acurácia: \033[0m' '\n',"%.4f" % accuracy_score(y_test, pred), '\n \n'
      '\033[1m  ROC AUC: \033[0m' '\n',"%.4f" % roc_auc_score(y_test, pred))

## Decision Tree

In [228]:
dtree = DecisionTreeClassifier(random_state= 101)

param_grid = {'max_features': ['sqrt', 'log2'],
              'ccp_alpha': [0.1, 0.01, 0.001],
              'max_depth' : [5, 6, 7, 8, 9],
              'criterion' :['gini', 'entropy']
}

CV_dtree = GridSearchCV(estimator=dtree, param_grid=param_grid, cv=5, verbose=True, n_jobs=-1)
CV_dtree.fit(X_train, y_train)

dtree_best_model = CV_dtree.best_estimator_
print(dtree_best_model)

Fitting 5 folds for each of 60 candidates, totalling 300 fits
DecisionTreeClassifier(ccp_alpha=0.001, criterion='entropy', max_depth=9,
                       max_features='sqrt', random_state=101)

In [230]:
dtree_final = DecisionTreeClassifier(ccp_alpha=0.001, criterion='entropy', max_depth=9, max_features='sqrt', random_state=101)
dtree_final.fit(X_train,y_train)
dtree_final_predictions = dtree_final.predict(X_test)

metricas(y_test, dtree_final_predictions)

  Relatório de classificação:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98     25668
           1       1.00      0.79      0.88      4638

    accuracy                           0.97     30306
   macro avg       0.98      0.89      0.93     30306
weighted avg       0.97      0.97      0.97     30306

  Matriz de confusão:
 [[25666     2]
 [  995  3643]]

  Acurácia:
 0.9671

  ROC AUC:
 0.8927

## Random Forest

In [234]:
rfc = RandomForestClassifier(random_state= 101)

param_grid = { 
    'n_estimators': [50, 100, 150],
    'max_features': ['sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 10, verbose= True, n_jobs=-1)
CV_rfc.fit(X_train, y_train)

rfc_best_model = CV_rfc.best_estimator_
print(rfc_best_model)

Fitting 10 folds for each of 60 candidates, totalling 600 fits
RandomForestClassifier(max_depth=5, n_estimators=50, random_state=101)

In [235]:
rfc_final=RandomForestClassifier(max_depth=5, n_estimators=50, random_state=101)
rfc_final.fit(X_train,y_train)
rfc_final_predictions = rfc_final.predict(X_test)

metricas(y_test, rfc_final_predictions)

  Relatório de classificação:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99     25668
           1       1.00      0.89      0.94      4638

    accuracy                           0.98     30306
   macro avg       0.99      0.94      0.97     30306
weighted avg       0.98      0.98      0.98     30306

  Matriz de confusão:
 [[25668     0]
 [  514  4124]]

  Acurácia:
 0.9830

  ROC AUC:
 0.9446